# release.toml

publish = false
push = false

tag-name = "v{{version}}"
tag-message = "Release v{{version}}"

pre-release-hook = [
  "git cliff -o CHANGELOG.md -t {{version}}",
  "git add CHANGELOG.md"
]
pre-release-commit-message = "Release v{{version}}"

allow-branch = ["main"]