# release.toml

publish = false
push = false

tag-name = "v{{version}}"
tag-message = "Release v{{version}}"

pre-release-hook = [
  "git",
  "cliff",
  "-o",
  "CHANGELOG.md",
]
pre-release-replacements = [
  { file = "CHANGELOG.md", search = ".*", replace = "{{changelog}}" },
]
pre-release-commit-message = "Release v{{version}}"

allow-branch = ["main"]
